package IHM;
import IHM.MainFormApplication;
import IHM.CreationContactFrame;
import IHM.ListeContactsFrame;
import core.Agent;
import core.Enseignant;
import core.Repertoire;
import core.Etudiant;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gabriel
 */
public class CreationContactFrame extends javax.swing.JFrame {
        private static MainFormApplication mainFrame;
        private Repertoire repertoire1;
        private Repertoire repertoire2;
        private Repertoire repertoire3;
    /**
     * Creates new form ContactFrame
     */
    public CreationContactFrame(MainFormApplication mainFrame) {
        initComponents();
            this.mainFrame = mainFrame;
            this.setVisible(false);
            mainFrame.setVisible(false);
            repertoire1 = new Repertoire();
            repertoire2 = new Repertoire();
            repertoire3 = new Repertoire();
        
    }
    
    private void activate(boolean a,boolean b,boolean c){
         //            activer,desactiver les champs de l'etudiant
            this.jTextField_title_cycle_etu.setVisible(a);
            this.jComboBox_cycle_etu.setVisible(a);
            this.jTextField_title_niveau_etu.setVisible(a);
            this.jComboBox_niveau_etu.setVisible(a);
     
//           activer, desctiver les champs de l'enseignant
            this.jComboBox_statut_ens.setVisible(b);
            this.jTextField__title_statut_ens.setVisible(b);
            
            
//            activer,desactiver les champs de l'agent        
            this.jTextField_title_salaire_agent.setVisible(c);
            this.jTextField_title_statut_agent.setVisible(c);
            this.jTextField_title_categorie_agent.setVisible(c);
            this.jTextField_title_indice_agent.setVisible(c);
            this.jTextField_title_occupation_agent.setVisible(c);
            this.jTextField_salaire_agent.setVisible(c);
            this.jComboBox_statut_agent.setVisible(c);
            this.jTextField_categorie_agent.setVisible(c);
            this.jTextField_indice_salaire_agent.setVisible(c);
            this.jTextField_occupation_agent.setVisible(c);
            
            
 //supprimer les indications
            this.jTextField_ind_etu.setVisible(false);
            this.jTextField_ind_ens.setVisible(false);
            this.jTextField_ind_agent.setVisible(false);
    }
    
  private String niv_etu(String niv_etu){
          int j = this.jComboBox_niveau_etu.getSelectedIndex();
               switch (j) {
                           case 0:
                                niv_etu="I";
                                break;
                            case 1:
                                niv_etu="II";
                                break;
                            case 2:
                                niv_etu="III";
                                break;
                            case 3:
                                niv_etu="VI";
                                break;
                            case 4:
                                niv_etu="V";
                                break;
                            default:
                                break;
               }
               return niv_etu;
  }
  
  private String statut_agent(String statut){
          int j = this.jComboBox_niveau_etu.getSelectedIndex();
               switch (j) {
                           case 0:
                                statut ="Temporaire";
                                break;
                            case 1:
                                statut ="Stagiaire";
                                break;
                            case 2:
                                statut ="Permanent";
                                break;
                            default:
                                break;
               }
               return statut;
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField21 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTextField_title_tel_num = new javax.swing.JTextField();
        jTextField_code = new javax.swing.JTextField();
        jTextField_title_code = new javax.swing.JTextField();
        jTextField_title_nom = new javax.swing.JTextField();
        jTextField_title_email = new javax.swing.JTextField();
        jTextField_title_adress = new javax.swing.JTextField();
        jTextField_title_date_naiss = new javax.swing.JTextField();
        jTextField_telNumber = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jTextField_nom = new javax.swing.JTextField();
        jTextField_dateNaiss = new javax.swing.JTextField();
        jButtonRetour = new javax.swing.JButton();
        jButton_valider = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox_poste = new javax.swing.JComboBox<>();
        jTextField_title_cycle_etu = new javax.swing.JTextField();
        jComboBox_cycle_etu = new javax.swing.JComboBox<>();
        jTextField_title_occupation_agent = new javax.swing.JTextField();
        jTextField_title_niveau_etu = new javax.swing.JTextField();
        jComboBox_niveau_etu = new javax.swing.JComboBox<>();
        jTextField_title_salaire_agent = new javax.swing.JTextField();
        jTextField_ind_agent = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField_ind_etu = new javax.swing.JTextField();
        jTextField__title_statut_ens = new javax.swing.JTextField();
        jComboBox_statut_ens = new javax.swing.JComboBox<>();
        jTextField_ind_ens = new javax.swing.JTextField();
        jTextField_title_statut_agent = new javax.swing.JTextField();
        jTextField_title_indice_agent = new javax.swing.JTextField();
        jTextField_title_categorie_agent = new javax.swing.JTextField();
        jComboBox_statut_agent = new javax.swing.JComboBox<>();
        jTextField14 = new javax.swing.JTextField();
        jTextField_indice_salaire_agent = new javax.swing.JTextField();
        jTextField_salaire_agent = new javax.swing.JTextField();
        jTextField_categorie_agent = new javax.swing.JTextField();
        jTextField_occupation_agent = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jTextField21.setEditable(false);
        jTextField21.setText("etudiants uniquement");
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bienvenue ,vous pouvez gerez vos contacts en toute securite", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(102, 102, 255))); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(255, 0, 255));
        jTextArea2.setText("Renseignez les champs pour creer un contact ");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTextField_title_tel_num.setEditable(false);
        jTextField_title_tel_num.setText("telNumber:");
        jTextField_title_tel_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_tel_numActionPerformed(evt);
            }
        });

        jTextField_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codeActionPerformed(evt);
            }
        });

        jTextField_title_code.setEditable(false);
        jTextField_title_code.setText("code :");
        jTextField_title_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_codeActionPerformed(evt);
            }
        });

        jTextField_title_nom.setEditable(false);
        jTextField_title_nom.setText("nom:");
        jTextField_title_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_nomActionPerformed(evt);
            }
        });

        jTextField_title_email.setEditable(false);
        jTextField_title_email.setText("email:");
        jTextField_title_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_emailActionPerformed(evt);
            }
        });

        jTextField_title_adress.setEditable(false);
        jTextField_title_adress.setText("adresse:");
        jTextField_title_adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_adressActionPerformed(evt);
            }
        });

        jTextField_title_date_naiss.setEditable(false);
        jTextField_title_date_naiss.setText("date de Naissance:");
        jTextField_title_date_naiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_date_naissActionPerformed(evt);
            }
        });

        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });

        jTextField_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nomActionPerformed(evt);
            }
        });

        jButtonRetour.setBackground(new java.awt.Color(255, 0, 0));
        jButtonRetour.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jButton_valider.setBackground(new java.awt.Color(102, 102, 255));
        jButton_valider.setForeground(new java.awt.Color(255, 255, 255));
        jButton_valider.setText("Valider");
        jButton_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_title_email, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_email))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_title_tel_num)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_telNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_title_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jTextField_nom))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_title_code, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_title_adress, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jTextField_code))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextField_title_date_naiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_dateNaiss, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_address))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_title_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_dateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_title_date_naiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_tel_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_telNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jComboBox_poste.setForeground(new java.awt.Color(255, 51, 51));
        jComboBox_poste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner un type de Contact ici", "Etudiant", "Enseignant", "Agent" }));
        jComboBox_poste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_posteActionPerformed(evt);
            }
        });

        jTextField_title_cycle_etu.setEditable(false);
        jTextField_title_cycle_etu.setText("Cycle de l'etudiant:");
        jTextField_title_cycle_etu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_cycle_etuActionPerformed(evt);
            }
        });

        jComboBox_cycle_etu.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox_cycle_etu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "licence", "ingenieur" }));
        jComboBox_cycle_etu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_cycle_etuActionPerformed(evt);
            }
        });

        jTextField_title_occupation_agent.setEditable(false);
        jTextField_title_occupation_agent.setText("occupation de l'Agent :");
        jTextField_title_occupation_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_occupation_agentActionPerformed(evt);
            }
        });

        jTextField_title_niveau_etu.setEditable(false);
        jTextField_title_niveau_etu.setText("Niveau de l'etudiant:");
        jTextField_title_niveau_etu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_niveau_etuActionPerformed(evt);
            }
        });

        jComboBox_niveau_etu.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox_niveau_etu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV", "V" }));

        jTextField_title_salaire_agent.setEditable(false);
        jTextField_title_salaire_agent.setText("Salaire de l'Agent :");
        jTextField_title_salaire_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_salaire_agentActionPerformed(evt);
            }
        });

        jTextField_ind_agent.setEditable(false);
        jTextField_ind_agent.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_ind_agent.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        jTextField_ind_agent.setForeground(new java.awt.Color(255, 51, 153));
        jTextField_ind_agent.setText("Agents uniquement:");
        jTextField_ind_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ind_agentActionPerformed(evt);
            }
        });

        jTextField20.setEditable(false);
        jTextField20.setText("etudiants uniquement");
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });

        jTextField_ind_etu.setEditable(false);
        jTextField_ind_etu.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_ind_etu.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        jTextField_ind_etu.setForeground(new java.awt.Color(255, 51, 153));
        jTextField_ind_etu.setText("etudiants uniquement");
        jTextField_ind_etu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ind_etuActionPerformed(evt);
            }
        });

        jTextField__title_statut_ens.setEditable(false);
        jTextField__title_statut_ens.setText("Statut de l'enseignant:");
        jTextField__title_statut_ens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField__title_statut_ensActionPerformed(evt);
            }
        });

        jComboBox_statut_ens.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox_statut_ens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacataire", "Permanent" }));
        jComboBox_statut_ens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_statut_ensActionPerformed(evt);
            }
        });

        jTextField_ind_ens.setEditable(false);
        jTextField_ind_ens.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_ind_ens.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        jTextField_ind_ens.setForeground(new java.awt.Color(255, 51, 153));
        jTextField_ind_ens.setText("enseignants uniquement:");
        jTextField_ind_ens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ind_ensActionPerformed(evt);
            }
        });

        jTextField_title_statut_agent.setEditable(false);
        jTextField_title_statut_agent.setText("Statut de l'Agent:");
        jTextField_title_statut_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_statut_agentActionPerformed(evt);
            }
        });

        jTextField_title_indice_agent.setEditable(false);
        jTextField_title_indice_agent.setText("indice de salaire de l'Agent :");
        jTextField_title_indice_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_indice_agentActionPerformed(evt);
            }
        });

        jTextField_title_categorie_agent.setEditable(false);
        jTextField_title_categorie_agent.setText("categorie de l'Agent :");
        jTextField_title_categorie_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_title_categorie_agentActionPerformed(evt);
            }
        });

        jComboBox_statut_agent.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox_statut_agent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temporaire", "Stagiaire", "Permanent" }));
        jComboBox_statut_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_statut_agentActionPerformed(evt);
            }
        });

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(255, 255, 255));
        jTextField14.setText("poste:");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jTextField_indice_salaire_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_indice_salaire_agentActionPerformed(evt);
            }
        });

        jTextField_salaire_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_salaire_agentActionPerformed(evt);
            }
        });

        jTextField_categorie_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_categorie_agentActionPerformed(evt);
            }
        });

        jTextField_occupation_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_occupation_agentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField__title_statut_ens)
                .addGap(24, 24, 24)
                .addComponent(jComboBox_statut_ens, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_title_statut_agent)
                    .addComponent(jTextField_title_salaire_agent))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jComboBox_statut_agent, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_salaire_agent, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField_title_categorie_agent)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_categorie_agent, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField_title_occupation_agent)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_occupation_agent, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_title_cycle_etu)
                            .addComponent(jTextField_title_niveau_etu))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_niveau_etu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_cycle_etu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField_title_indice_agent)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField_indice_salaire_agent, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ind_etu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ind_ens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ind_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_poste, 0, 360, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTextField20)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_ind_etu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_cycle_etu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_cycle_etu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_niveau_etu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_niveau_etu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_ind_ens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField__title_statut_ens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_statut_ens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_ind_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_salaire_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_salaire_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_statut_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_statut_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_categorie_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_categorie_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_indice_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_indice_salaire_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_title_occupation_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_occupation_agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(289, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_title_tel_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_tel_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_tel_numActionPerformed

    private void jTextField_title_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_codeActionPerformed

    private void jTextField_title_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_nomActionPerformed

    private void jTextField_title_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_emailActionPerformed

    private void jTextField_title_adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_adressActionPerformed

    private void jTextField_title_date_naissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_date_naissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_date_naissActionPerformed

    private void jTextField_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codeActionPerformed

    private void jTextField_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nomActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    private void jComboBox_posteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_posteActionPerformed
        // TODO add your handling code here:
        int index = jComboBox_poste.getSelectedIndex();
        
            switch (index) {
                case 0:
                    this.jButton_valider.setEnabled(false);
                    activate(false,false,false);
                    break;
                case 1:
                    activate(true,false,false);
                    break;
                case 2:
                    activate(false,true,false);
                    break;
                case 3:
                    activate(false,false,true);
                    break;
                default:
                    break;
            }
        
    }//GEN-LAST:event_jComboBox_posteActionPerformed

    private void jTextField_title_cycle_etuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_cycle_etuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_cycle_etuActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jComboBox_cycle_etuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_cycle_etuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_cycle_etuActionPerformed

    private void jTextField_title_occupation_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_occupation_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_occupation_agentActionPerformed

    private void jTextField_title_niveau_etuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_niveau_etuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_niveau_etuActionPerformed

    private void jTextField_title_salaire_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_salaire_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_salaire_agentActionPerformed

    private void jTextField_ind_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ind_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ind_agentActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField_ind_etuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ind_etuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ind_etuActionPerformed

    private void jTextField__title_statut_ensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField__title_statut_ensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField__title_statut_ensActionPerformed

    private void jComboBox_statut_ensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_statut_ensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_statut_ensActionPerformed

    private void jTextField_ind_ensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ind_ensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ind_ensActionPerformed

    private void jTextField_title_statut_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_statut_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_statut_agentActionPerformed

    private void jTextField_title_indice_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_indice_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_indice_agentActionPerformed

    private void jTextField_title_categorie_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_title_categorie_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_title_categorie_agentActionPerformed

    private void jComboBox_statut_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_statut_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_statut_agentActionPerformed

    private void jTextField_indice_salaire_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_indice_salaire_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_indice_salaire_agentActionPerformed

    private void jTextField_salaire_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_salaire_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_salaire_agentActionPerformed

    private void jTextField_occupation_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_occupation_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_occupation_agentActionPerformed

    private void jTextField_categorie_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_categorie_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_categorie_agentActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        // TODO add your handling code here:
           this.mainFrame.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jButton_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_validerActionPerformed
            String code = this.jTextField_code.getText();
            String nom = this.jTextField_nom.getText();
            String date = this.jTextField_dateNaiss.getText();
            String address = this.jTextField_address.getText();
            String email = this.jTextField_email.getText();
            String telNumber = this.jTextField_telNumber.getText();
            
            //etudiant
            String cycle_etu = "";
            String niv_etu = "";
            
            //enseignant
            String statut_ens = "";
            
            //agent
            String salaire_agent = "";
            String statut_agent = "";
            String categorie_agent = "";
            String indice_agent = "";
            String occupation_agent = "";
            int index = jComboBox_poste.getSelectedIndex();
            switch (index) {
                        case 1:{
                                    //recuperer cycle etudiant
                                int i = this.jComboBox_cycle_etu.getSelectedIndex();
                                if(i==0){
                                    cycle_etu = "licence";
                                }else if(i == 1){
                                     cycle_etu = "ingenieur";
                                }
                                //recuperer niveau etudiant 
                                  niv_etu = this.niv_etu(niv_etu);  
                                }
                                    //ajout au repertoire
                                  repertoire1.ajouter(new Etudiant(code,nom,date,address,email,telNumber,cycle_etu,niv_etu));
                                  
                            break;
                        case 2://recuperer le statut de l'enseignant
                             int i = this.jComboBox_statut_ens.getSelectedIndex();
                                if(i==0){
                                    statut_ens = "Vacataire";
                                }else if(i == 1){
                                     statut_ens = "Permanent";
                                }
                                
                                    //ajout au repertoire
                                  repertoire2.ajouter(new Enseignant(code,nom,date,address,email,telNumber,statut_ens));
                            break;
                        case 3:{
                            //salaire,categorie,indice de salaire,occupation de l'agent
                                salaire_agent= this.jTextField_salaire_agent.getText();
                                categorie_agent =  this.jTextField_categorie_agent.getText();
                                indice_agent =  this.jTextField_indice_salaire_agent.getText();
                                occupation_agent = this.jTextField_occupation_agent.getText();
                            //statut de l'agent
                             statut_agent = this.statut_agent(statut_agent);                
                            }
                                //ajout au repertoire
                                  repertoire3.ajouter(new Agent(code,nom,date,address,email,telNumber,salaire_agent,statut_agent,categorie_agent,indice_agent,occupation_agent));
                             break;
                default:
                    break;
            }
            
                    System.out.println("--------------etudiants :------------------- " );
                                repertoire1.afficher();

                    System.out.println("--------------enseignants :------------------- " );
                            repertoire2.afficher();
                    System.out.println("--------------agents :------------------- " );
                            repertoire3.afficher();
        
    }//GEN-LAST:event_jButton_validerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreationContactFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreationContactFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreationContactFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreationContactFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CreationContactFrame(mainFrame).setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButton_valider;
    private javax.swing.JComboBox<String> jComboBox_cycle_etu;
    private javax.swing.JComboBox<String> jComboBox_niveau_etu;
    private javax.swing.JComboBox<String> jComboBox_poste;
    private javax.swing.JComboBox<String> jComboBox_statut_agent;
    private javax.swing.JComboBox<String> jComboBox_statut_ens;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField__title_statut_ens;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_categorie_agent;
    private javax.swing.JTextField jTextField_code;
    private javax.swing.JTextField jTextField_dateNaiss;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_ind_agent;
    private javax.swing.JTextField jTextField_ind_ens;
    private javax.swing.JTextField jTextField_ind_etu;
    private javax.swing.JTextField jTextField_indice_salaire_agent;
    private javax.swing.JTextField jTextField_nom;
    private javax.swing.JTextField jTextField_occupation_agent;
    private javax.swing.JTextField jTextField_salaire_agent;
    private javax.swing.JTextField jTextField_telNumber;
    private javax.swing.JTextField jTextField_title_adress;
    private javax.swing.JTextField jTextField_title_categorie_agent;
    private javax.swing.JTextField jTextField_title_code;
    private javax.swing.JTextField jTextField_title_cycle_etu;
    private javax.swing.JTextField jTextField_title_date_naiss;
    private javax.swing.JTextField jTextField_title_email;
    private javax.swing.JTextField jTextField_title_indice_agent;
    private javax.swing.JTextField jTextField_title_niveau_etu;
    private javax.swing.JTextField jTextField_title_nom;
    private javax.swing.JTextField jTextField_title_occupation_agent;
    private javax.swing.JTextField jTextField_title_salaire_agent;
    private javax.swing.JTextField jTextField_title_statut_agent;
    private javax.swing.JTextField jTextField_title_tel_num;
    // End of variables declaration//GEN-END:variables
}
